Repository riscv-steel/riscv-steel, pull requests merged in 2024-02, with the labels that each got.

#35 Use riscv32-unknown-elf-objcopy to generate Verilog memory init files instead of octal dump (od)
  demos/examples/hello_world/software/.gitignore
  demos/examples/hello_world/software/Makefile
  demos/examples/hello_world/software/build/hello_world.hex
  software/template_project/Makefile
Labels: enhancement

#52 Fixed the size of regions for D0_RAM, D2_MTIMER, D3_GPIO
  hardware/soc/rvsteel_soc.v
Labels: bug

#57 Ref unsized constant numbers
  hardware/core/tests/verilator/unit_tests.v
  hardware/gpio/rvsteel_gpio.v
  hardware/mtimer/rvsteel_mtimer.v
  hardware/mtimer/tests/test_mtimer.py
Labels: refactoring
